/**
 * Label map per event type.
 * Add new event types here as keys — all components will pick them up automatically.
 * Default is always 'wedding', so existing invitations are unaffected.
 */
export const EVENT_LABELS = {
  wedding: {
    heroEyebrow: 'Wedding Celebration',
    heroHeading: 'We Are Getting Married',
    heroFamiliesLine: 'Together with their families invite you to their wedding',
    heroFamiliesIcal: 'Together with their families\\, invite you to their wedding.',
    coupleRevealTagline: 'Are Getting Married',
    timelineEyebrow: 'The Big Day',
    timelineHeading: 'Wedding Timeline',
    countdownLabel: 'Counting down to the big day',
    countdownHeading: 'The Celebration Begins In',
    rsvpMessageHeader: '💍 *Wedding Invitation Reply* 💍',
    rsvpMessageHeaderAlt: '💍 *Wedding RSVP* 💍',
    storyFooter: 'Happily Ever After',
    storyHeading6: 'Our Love Story',
    storyCaption7: 'Moments Together',
    storySection: 'Our Story',
    coverRevealTagline: "We're getting married!",
    layout8JoinUs: 'Join us for the wedding of',
    layout8EternalLabel: 'Eternal Love',
    layout8GalleryLabel: 'Love In Frames',
    layout11HeroSmall: 'The celebration takes place at',
    layout11HeroBig: '',
    envelopeTitle: 'A Wedding Invitation',
    photoLabel: 'Our Wedding Day',
    eventDetailsSubtitle: 'Lovely moments together',
    navNames: '',
  },
  engagement: {
    heroEyebrow: 'Engagement Celebration',
    heroHeading: 'We Are Getting Engaged',
    heroFamiliesLine: 'Together with their families invite you to their engagement',
    heroFamiliesIcal: 'Together with their families\\, invite you to their engagement.',
    coupleRevealTagline: 'Are Getting Engaged',
    timelineEyebrow: 'The Big Day',
    timelineHeading: 'Engagement Timeline',
    countdownLabel: 'Counting down to the big day',
    countdownHeading: 'The Celebration Begins In',
    rsvpMessageHeader: '💌 *Engagement Invitation Reply* 💌',
    rsvpMessageHeaderAlt: '💌 *Engagement RSVP* 💌',
    storyFooter: 'And So It Begins',
    storyHeading6: 'Our Love Story',
    storyCaption7: 'Moments Together',
    storySection: 'Our Story',
    coverRevealTagline: "We're getting engaged!",
    layout8JoinUs: 'Join us for the engagement of',
    layout8EternalLabel: 'Our Journey',
    layout8GalleryLabel: 'Moments In Frames',
    layout11HeroSmall: 'The celebration takes place at',
    layout11HeroBig: '',
    envelopeTitle: 'An Engagement Invitation',
    photoLabel: 'Our Engagement Day',
    eventDetailsSubtitle: 'Lovely moments together',
    navNames: '',
  },
  birthday: {
    heroEyebrow: 'Birthday Celebration',
    heroHeading: 'Join the Celebration',
    heroFamiliesLine: 'Together with family and friends invite you to the birthday celebration',
    heroFamiliesIcal: 'Together with family and friends\\, invite you to the birthday celebration.',
    coupleRevealTagline: 'Is Celebrating a Birthday!',
    timelineEyebrow: 'The Big Day',
    timelineHeading: 'Birthday Schedule',
    countdownLabel: 'Counting down to the big day',
    countdownHeading: 'The Party Begins In',
    rsvpMessageHeader: '🎂 *Birthday Invitation Reply* 🎂',
    rsvpMessageHeaderAlt: '🎂 *Birthday RSVP* 🎂',
    storyFooter: 'Making Memories',
    storyHeading6: 'A Life Worth Celebrating',
    storyCaption7: 'Golden Moments',
    storySection: 'The Journey',
    coverRevealTagline: 'You are invited to the birthday bash!',
    layout8JoinUs: 'Join us in celebrating',
    layout8EternalLabel: 'A Beautiful Journey',
    layout8GalleryLabel: 'Captured Memories',
    layout11HeroSmall: 'The party takes place at',
    layout11HeroBig: '',
    envelopeTitle: 'A Birthday Invitation',
    photoLabel: 'Birthday Celebration',
    eventDetailsSubtitle: 'Let the celebrations begin',
    navNames: '',
  },
  general: {
    heroEyebrow: 'Special Event',
    heroHeading: 'You Are Invited',
    heroFamiliesLine: 'We cordially invite you to this special occasion',
    heroFamiliesIcal: 'We cordially invite you to this special occasion.',
    coupleRevealTagline: 'Cordially Invites You',
    timelineEyebrow: 'Event Day',
    timelineHeading: 'Event Schedule',
    countdownLabel: 'Counting down to the event',
    countdownHeading: 'The Event Begins In',
    rsvpMessageHeader: '📩 *Event Invitation Reply* 📩',
    rsvpMessageHeaderAlt: '📩 *Event RSVP* 📩',
    storyFooter: 'We Hope to See You There',
    storyHeading6: 'About This Event',
    storyCaption7: 'Special Moments',
    storySection: 'Our Story',
    coverRevealTagline: 'You have been invited!',
    layout8JoinUs: 'Join us for',
    layout8EternalLabel: 'An Unforgettable Evening',
    layout8GalleryLabel: 'Event Gallery',
    layout11HeroSmall: 'The event takes place at',
    layout11HeroBig: '',
    envelopeTitle: 'An Invitation',
    photoLabel: 'Special Event',
    eventDetailsSubtitle: 'A special occasion',
    navNames: '',
  },
};

/**
 * Returns the label set for the given eventType.
 * Falls back to 'wedding' labels if the type is unknown or missing,
 * so all existing invitations without an event_meta record work as before.
 */
export function getLabels(eventType) {
  return EVENT_LABELS[eventType] || EVENT_LABELS.wedding;
}
